num_moves_range:
  min: 10
  max: 150

num_moves_per_puzzle_defaults:
  2x2: 10
  3x3: 25

theme_list:
  - Dracula
  - Everforest-Light
  - Everforest-Dark
  - Gruvbox-Light
  - Gruvbox-Dark
  - Nord-Aurora
  - Nord-Frost
  - Nord-PolarNight
  - PaperColor-Light
  - PaperColor-Dark

puzzle_type_list:
  - 2x2
  - 3x3

min_window_size:
  width: 400
  height: 230
